### ISSUE TITLE
v1.5.0 affinity overlay is oversized and big even for 8c/16t cpu's (ryzen 7800x3d example)

### ISSUE THREAD

**Issue by wazerstar** [spddl/GoInterruptPolicy#10]
New Beta
![oJ7LSv6](https://github.com/user-attachments/assets/b7394647-b8e2-4279-9b94-4d6615cfa863)

Old had better overview, 

![HiHYEeb](https://github.com/user-attachments/assets/cec2ea90-eba0-4e19-b592-d2b2520fd58e)

I think that having sort of this example, pushing CCD0 or P cores more to the left and CCD1/x or E cores to the right just expanding will have a better overview over it all..

Example
![bPZ0eXw](https://github.com/user-attachments/assets/4e2fad68-ee3f-4a71-90d7-d91f701e967c)

**Comment by spddl** [comment]
Do we really need 2 issues on this layout topic? Please close this one or the other. https://github.com/spddl/GoInterruptPolicy/issues/8

I know that the implementation is not yet the best and that it is still a beta version. There are too many variants to simply put them in a box. But you can make this window larger or use the scrollbars.
![out2](https://github.com/user-attachments/assets/334e208c-d3ad-41a4-94aa-3790cc710b36)

With an AMD Ryzen 9 5900X, the area expands more towards the bottom.
![image](https://github.com/user-attachments/assets/e34ef260-cb6d-4474-af52-71d2750f574f)
