### ISSUE TITLE
Can't sort by interrupt type

### ISSUE THREAD

**Issue by xcasxcursex** [spddl/GoInterruptPolicy#2]
Clicking on any of the column headers allows us to sort the list by that column's value (the usual) but doesn't work for the "Interrup Type" column. Also, is that a typo? ('interrup' is missing a 't') I see it in a few places. Maybe autocomplete is the cause of that.

**Comment by spddl** [comment]
thank you, both are fixed.

**Comment by xcasxcursex** [comment]
Thank you! Nice app man
