### ISSUE TITLE
Feature Request > Option view only to show devices that generate interrupts.

### ISSUE THREAD

**Issue by wazerstar** [spddl/GoInterruptPolicy#7]
First of all thanks for this amazing tool, I really like it.

I have one request that would make it a lot easier to navigate through the list and only select devices that generates interrupt to avoid mixing stuff you should not touch with at all. 

I'm not sure if it can be done, but if it can, maybe you could look into it.

**Comment by spddl** [comment]
The tool does not record interrupts.
But if you are interested in this, take a look at [LatencyMon](https://www.resplendence.com/latencymon) or the [Windows Performance Analyzer](https://learn.microsoft.com/en-us/windows-hardware/test/wpt/windows-performance-analyzer)

**Comment by TsuZing** [comment]
You may have misunderstood intent of this issue. For x86, typically only PCI and ISA devices can generate IRQ, and Windows can only configure IRQ for PCI devices (IRQ for ISA devices can only configured by kernel). So you can simply filter by device object name (\Device\NTPNP_PCI*). Alternatively, you can use some Windows APIs to check if a device has IRQ, as Device Manager's Resources tab. However, this will also list ISA devices, and modifying IRQ of ISA devices will have no effect.

**Comment by spddl** [comment]
Any suggestions? Feedback?
There are also new columns: “Class” and “IRQ Lanes”

[GoInterruptPolicy.zip](https://github.com/user-attachments/files/26288375/GoInterruptPolicy.zip)

<img width="1499" height="593" alt="Image" src="https://github.com/user-attachments/assets/8e419903-7a5a-4f4a-af14-7e5f9521ae24" />

**Comment by spddl** [comment]
This is now included in version 1.9.0. However, I'm not sure if that covers all of them. If there are any other devices that use the IRQ policy, please feel free to reopen the issue.

**Comment by TsuZing** [comment]
It works fine, thanks! However, if you are concerned about any issues, you might add a "Show all devices" checkbox.

**Comment by spddl** [comment]
Sure, you could, but you wouldn't need to if it's already "correct" :D
You can still use an older version for setting up and testing other devices.
